['Event_00114_00001_Trigger'];
SceneEnter(106);
PartySetPos(8, 27, 0);
FadeOut(0);

['Event_00114_00002_Trigger'];
SceneEnter(106);
PartySetPos(30, 11, 0);
FadeOut(0);

['Event_00114_00003_Auto'];
GotoWithProbability(5, "");
EventAnimate(Direction.Southwest);
EventAnimate(Direction.Southwest);
EventAnimate(Direction.Southwest);
EventAnimate(Direction.Southwest);
ReplaceAndPause();
EventAnimate(Direction.Southwest);
GotoWithProbability(10, "");
EventAnimate(Direction.Northwest);
EventAnimate(Direction.Northwest);
EventAnimate(Direction.Northwest);
EventAnimate(Direction.Northwest);
EventAnimate(Direction.Northwest);
EventAnimate(Direction.Northwest);
EventAnimate(Direction.Northwest);
ReplaceAndPause();
EventAnimate(Direction.Northwest);
WaitEventAutoScriptRun(2, false, false);
GotoWithProbability(5, "");
EventAnimate(Direction.Southeast);
WaitEventAutoScriptRun(2, false, false);
EventAnimate(Direction.Southeast);
EventAnimate(Direction.Southeast);
EventAnimate(Direction.Southwest);
EventAnimate(Direction.Southwest);
EventAnimate(Direction.Southwest);
GotoWithProbability(8, "");
EventAnimate(Direction.Southeast);
EventAnimate(Direction.Southeast);
EventAnimate(Direction.Southeast);
EventAnimate(Direction.Southeast);
EventAnimate(Direction.Southeast);
EventAnimate(Direction.Northeast);
EventAnimate(Direction.Northeast);
EventAnimate(Direction.Northeast);
EventAnimate(Direction.Northeast);
EventAnimate(Direction.Northeast);
EventAnimate(Direction.Northeast);
ReplaceAndPause();
EventAnimate(Direction.Northeast);
GotoWithProbability(10, "");
EventAnimate(Direction.Northeast);
ReplaceAndPauseWithNop("Event_00114_00003_Auto", 0);

